### ISSUE TITLE
Support parsing of streaming rpc endpoints 

### ISSUE THREAD

**Issue by jjttjj** [s-expresso/rubberbuf#4]
When I try to call `rubberbuf.core/protoc` on a file that has a streaming grpc request or response I get an error. This example file:

```protobuf
syntax = "proto3";

package example;

service StreamingService {
  rpc SingleResponse(SingleRequest) returns (SingleResponse);

  rpc ServerSideStream(StreamRequest) returns (stream StreamResponse);
}

message SingleRequest {
  string payload = 1;
}

message SingleResponse {
  string payload = 1;
}

message StreamRequest {
  string request_data = 1;
}

message StreamResponse {
  string response_data = 1;
}
```

Results in this error:

```
Exception stream_example.proto: Parse error at line 10, column 55:
  rpc ServerSideStream(StreamRequest) returns (stream StreamResponse);
                                                      ^
Expected one of:
)
//
#"(\/\*)[\s\S]*?(\*\/)"
#"\s+"
.
```
I'm just talking about allowing it to parse these files so I can use the protocol buffer message types in the same file, I'm not suggesting any grpc features be added.
I realize that as a protocol buffer library rubberbuf might not necessarily support all the grpc syntax, but since I've found that in practice it already works for non-streaming grpc usage, that maybe you would want to allow the streaming ones as well.

Thanks! I find clojobuf to be great so far and am really looking forward to fully replacing my existing Clojure protocol buffer code 😃

**Comment by st-cheewah** [comment]
Thanks for informing and the detailed info. It is now fixed in rubberbuf, and also clojobuf is updated to use the fixed version of rubberbuf.

PS: just fixed my lack of github notification by watching my own projects, should make me more responsive going forward :)

**Comment by jjttjj** [comment]
It's working for me now, thanks for the fix!
